server:
  host: 127.0.0.1         # 监听的ip地址
  port: 8080              # 监听的端口

db:                       # 数据库
  host: 127.0.0.1
  port: 3306
  user: root
  password: example
  database: jx_erp

jsonwebtoken:
  client:
    secret: "client"              # 密钥
    overdue: 86400                # 过期时间 秒
  admin:
    secret: "todo"               # 密钥
    overdue: 86400                # 过期时间 秒
log:
  writers: file,stdout
  logger_level: INFO
  logger_file: log/logs.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7